name: barcode scanner
description: A Flutter project using barcode scanner package. Shows barcode text on home screen after scanning.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: "^1.0.0"
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
